site_name:        GeneMANIA.jl
repo_url:         https://github.com/memoiry/GeneMANIA.jl/
site_description: Repo for GeneMANIA.jl.
site_author:      memoiry

docs_dir: 'build'

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code

docs_dir: 'build'

pages:
  - Home: index.md
  - Getting Start: dev/initial.md
  - Algorithms: 
    - Network Integration: algo/network_integration.md 
    - Label Propagation: algo/label_propagation.md
  - Contributions: user/contributions.md